/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuItem;

/**
 *
 * @author Davidson
 */
public class P0000View extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public P0000View() {
        initComponents();
        setLocationRelativeTo(getParent());
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        manterRepublica = new javax.swing.JMenuItem();
        manterMorador = new javax.swing.JMenuItem();
        confirmarSolucaoDeReclamacoesSolucoes = new javax.swing.JMenuItem();
        convidarMoradoresAceitarConvite = new javax.swing.JMenuItem();
        criarRepublica = new javax.swing.JMenuItem();
        buscarVagaRepublica = new javax.swing.JMenuItem();
        consultarResultadoMensal = new javax.swing.JMenuItem();
        manterReclamacoesSugestoes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        manterPerfil = new javax.swing.JMenuItem();
        aceitarConvite = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        manterTarefas = new javax.swing.JMenuItem();
        registrarConclusaoDaTarefa = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        manterReceitasEDespesas = new javax.swing.JMenuItem();
        fazerEstornoDeLancamentos = new javax.swing.JMenuItem();
        consultarMinhasReceitasEDespesas = new javax.swing.JMenuItem();
        registrarPagamentoDeReceitaOuDespesa = new javax.swing.JMenuItem();
        botaoSair = new javax.swing.JMenu();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("República");

        manterRepublica.setText("Manter república");
        manterRepublica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manterRepublicaActionPerformed(evt);
            }
        });
        jMenu1.add(manterRepublica);

        manterMorador.setText("Manter moradores");
        manterMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manterMoradorActionPerformed(evt);
            }
        });
        jMenu1.add(manterMorador);

        confirmarSolucaoDeReclamacoesSolucoes.setText("Confirmar solução de reclamações / sugestões");
        confirmarSolucaoDeReclamacoesSolucoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarSolucaoDeReclamacoesSolucoesActionPerformed(evt);
            }
        });
        jMenu1.add(confirmarSolucaoDeReclamacoesSolucoes);

        convidarMoradoresAceitarConvite.setText("Convidar moradores/ Aceitar convite");
        convidarMoradoresAceitarConvite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convidarMoradoresAceitarConviteActionPerformed(evt);
            }
        });
        jMenu1.add(convidarMoradoresAceitarConvite);

        criarRepublica.setText("Criar república");
        criarRepublica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarRepublicaActionPerformed(evt);
            }
        });
        jMenu1.add(criarRepublica);

        buscarVagaRepublica.setText("Buscar vagas");
        jMenu1.add(buscarVagaRepublica);

        consultarResultadoMensal.setText("Consultar resultado mensal");
        jMenu1.add(consultarResultadoMensal);

        manterReclamacoesSugestoes.setText("Manter reclamações / sugestões");
        jMenu1.add(manterReclamacoesSugestoes);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Morador");

        manterPerfil.setText("Manter perfil");
        manterPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manterPerfilActionPerformed(evt);
            }
        });
        jMenu2.add(manterPerfil);

        aceitarConvite.setText("Aceitar convite");
        aceitarConvite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceitarConviteActionPerformed(evt);
            }
        });
        jMenu2.add(aceitarConvite);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Tarefas");

        manterTarefas.setText("Manter tarefas");
        manterTarefas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manterTarefasActionPerformed(evt);
            }
        });
        jMenu3.add(manterTarefas);

        registrarConclusaoDaTarefa.setText("Registrar conclusão da tarefa");
        registrarConclusaoDaTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarConclusaoDaTarefaActionPerformed(evt);
            }
        });
        jMenu3.add(registrarConclusaoDaTarefa);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Lançamentos");

        manterReceitasEDespesas.setText("Manter receitas e despesas");
        manterReceitasEDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manterReceitasEDespesasActionPerformed(evt);
            }
        });
        jMenu4.add(manterReceitasEDespesas);

        fazerEstornoDeLancamentos.setText("Fazer estorno de lançamentos");
        fazerEstornoDeLancamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fazerEstornoDeLancamentosActionPerformed(evt);
            }
        });
        jMenu4.add(fazerEstornoDeLancamentos);

        consultarMinhasReceitasEDespesas.setText("Consultar minhas receitas e despesas");
        consultarMinhasReceitasEDespesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarMinhasReceitasEDespesasActionPerformed(evt);
            }
        });
        jMenu4.add(consultarMinhasReceitasEDespesas);

        registrarPagamentoDeReceitaOuDespesa.setText("Registrar pagamento de receita ou despesas");
        jMenu4.add(registrarPagamentoDeReceitaOuDespesa);

        jMenuBar1.add(jMenu4);

        botaoSair.setText("Sair");
        jMenuBar1.add(botaoSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 1029, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manterRepublicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manterRepublicaActionPerformed
    }//GEN-LAST:event_manterRepublicaActionPerformed

    private void manterMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manterMoradorActionPerformed
    }//GEN-LAST:event_manterMoradorActionPerformed

    private void confirmarSolucaoDeReclamacoesSolucoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarSolucaoDeReclamacoesSolucoesActionPerformed
    }//GEN-LAST:event_confirmarSolucaoDeReclamacoesSolucoesActionPerformed

    private void convidarMoradoresAceitarConviteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convidarMoradoresAceitarConviteActionPerformed
    }//GEN-LAST:event_convidarMoradoresAceitarConviteActionPerformed

    private void criarRepublicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarRepublicaActionPerformed
    }//GEN-LAST:event_criarRepublicaActionPerformed

    private void manterPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manterPerfilActionPerformed
    }//GEN-LAST:event_manterPerfilActionPerformed

    private void aceitarConviteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceitarConviteActionPerformed
    }//GEN-LAST:event_aceitarConviteActionPerformed

    private void manterTarefasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manterTarefasActionPerformed
    }//GEN-LAST:event_manterTarefasActionPerformed

    private void registrarConclusaoDaTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarConclusaoDaTarefaActionPerformed
    }//GEN-LAST:event_registrarConclusaoDaTarefaActionPerformed

    private void manterReceitasEDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manterReceitasEDespesasActionPerformed
    }//GEN-LAST:event_manterReceitasEDespesasActionPerformed

    private void fazerEstornoDeLancamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fazerEstornoDeLancamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fazerEstornoDeLancamentosActionPerformed

    private void consultarMinhasReceitasEDespesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarMinhasReceitasEDespesasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consultarMinhasReceitasEDespesasActionPerformed

    public JMenuItem getCriarRepublica() {
        return criarRepublica;
    }

    public JMenuItem getManterRepublica() {
        return manterRepublica;
    }

    public JMenuItem getAdicionarPerfil() {
        return manterPerfil;
    }

    public JMenuItem getManterMorador() {
        return manterMorador;
    }

    public JDesktopPane getDesktop() {
        return Desktop;
    }

    public JMenuItem getBuscarVagaRepublica() {
        return buscarVagaRepublica;
    }

    public JMenu getBotaoSair() {
        return botaoSair;
    }

    public JMenuItem getAceitarConvite() {
        return aceitarConvite;
    }

    public JMenuItem getConfirmarSolucaoDeReclamacoesSolucoes() {
        return confirmarSolucaoDeReclamacoesSolucoes;
    }

    public JMenuItem getConsultarMinhasReceitasEDespesas() {
        return consultarMinhasReceitasEDespesas;
    }

    public JMenuItem getConsultarResultadoMensal() {
        return consultarResultadoMensal;
    }

    public JMenuItem getConvidarMoradoresAceitarConvite() {
        return convidarMoradoresAceitarConvite;
    }

    public JMenuItem getFazerEstornoDeLancamentos() {
        return fazerEstornoDeLancamentos;
    }

    public JMenuItem getManterPerfil() {
        return manterPerfil;
    }

    public JMenuItem getManterReceitasEDespesas() {
        return manterReceitasEDespesas;
    }

    public JMenuItem getManterReclamacoesSugestoes() {
        return manterReclamacoesSugestoes;
    }

    public JMenuItem getManterTarefas() {
        return manterTarefas;
    }

    public JMenuItem getRegistrarConclusaoDaTarefa() {
        return registrarConclusaoDaTarefa;
    }

    public JMenuItem getRegistrarPagamentoDeReceitaOuDespesa() {
        return registrarPagamentoDeReceitaOuDespesa;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuItem aceitarConvite;
    private javax.swing.JMenu botaoSair;
    private javax.swing.JMenuItem buscarVagaRepublica;
    private javax.swing.JMenuItem confirmarSolucaoDeReclamacoesSolucoes;
    private javax.swing.JMenuItem consultarMinhasReceitasEDespesas;
    private javax.swing.JMenuItem consultarResultadoMensal;
    private javax.swing.JMenuItem convidarMoradoresAceitarConvite;
    private javax.swing.JMenuItem criarRepublica;
    private javax.swing.JMenuItem fazerEstornoDeLancamentos;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem manterMorador;
    private javax.swing.JMenuItem manterPerfil;
    private javax.swing.JMenuItem manterReceitasEDespesas;
    private javax.swing.JMenuItem manterReclamacoesSugestoes;
    private javax.swing.JMenuItem manterRepublica;
    private javax.swing.JMenuItem manterTarefas;
    private javax.swing.JMenuItem registrarConclusaoDaTarefa;
    private javax.swing.JMenuItem registrarPagamentoDeReceitaOuDespesa;
    // End of variables declaration//GEN-END:variables

}
