/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.ManterRepublica;

import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Davidson
 */
public class P0101 extends javax.swing.JInternalFrame {

    /**
     * Creates new form P0101
     */
    public P0101() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        endereco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bairro = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cep = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pontoDeReferencia = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        localizacaoGeografica = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        numero = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        vantagens = new javax.swing.JTextArea();
        despesasMediasMorador = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        totalVagas = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        vagasOcupadas = new javax.swing.JTextField();
        vagasDisponiveis = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        dataFundacao = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        codigoDeEtica = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        confirmar = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        endereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enderecoActionPerformed(evt);
            }
        });
        jPanel1.add(endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 33, 619, -1));

        jLabel3.setText("Logradouro:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 16, -1, -1));

        bairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bairroActionPerformed(evt);
            }
        });
        jPanel1.add(bairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 81, 711, -1));

        jLabel6.setText("Bairro:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 64, -1, -1));

        cep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cepActionPerformed(evt);
            }
        });
        jPanel1.add(cep, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 177, 206, -1));

        jLabel4.setText("CEP:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 160, -1, -1));

        pontoDeReferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pontoDeReferenciaActionPerformed(evt);
            }
        });
        jPanel1.add(pontoDeReferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 129, 711, -1));

        jLabel5.setText("Ponto de Referência:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 112, -1, -1));

        localizacaoGeografica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localizacaoGeograficaActionPerformed(evt);
            }
        });
        jPanel1.add(localizacaoGeografica, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 177, 499, -1));

        jLabel7.setText("Localização Geográfica:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 160, -1, -1));
        jPanel1.add(numero, new org.netbeans.lib.awtextra.AbsoluteConstraints(641, 33, 86, -1));

        jLabel14.setText("Número");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(641, 16, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 740, 210));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados da República"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Data de Fundação:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 16, -1, -1));

        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });
        jPanel2.add(nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 36, 477, -1));

        jLabel1.setText("Nome:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 19, -1, -1));

        jLabel8.setText("Vantagens:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 117, -1, -1));

        vantagens.setColumns(20);
        vantagens.setRows(5);
        jScrollPane1.setViewportView(vantagens);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 137, 346, 140));

        despesasMediasMorador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despesasMediasMoradorActionPerformed(evt);
            }
        });
        jPanel2.add(despesasMediasMorador, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 85, 170, -1));

        jLabel9.setText("Despesas Médias/Morador:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 68, -1, -1));

        totalVagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalVagasActionPerformed(evt);
            }
        });
        jPanel2.add(totalVagas, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 85, 170, -1));

        jLabel10.setText("Total de Vagas:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 68, -1, -1));

        jLabel11.setText("Vagas Ocupadas:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 68, -1, -1));

        vagasOcupadas.setEditable(false);
        vagasOcupadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vagasOcupadasActionPerformed(evt);
            }
        });
        jPanel2.add(vagasOcupadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(544, 85, 170, -1));

        vagasDisponiveis.setEditable(false);
        vagasDisponiveis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vagasDisponiveisActionPerformed(evt);
            }
        });
        jPanel2.add(vagasDisponiveis, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 85, 170, -1));

        jLabel12.setText("Vagas Disponíveis:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 68, -1, -1));

        dataFundacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataFundacaoActionPerformed(evt);
            }
        });
        jPanel2.add(dataFundacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 36, 215, -1));

        codigoDeEtica.setColumns(20);
        codigoDeEtica.setRows(5);
        jScrollPane2.setViewportView(codigoDeEtica);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 137, 346, 140));

        jLabel13.setText("Código de Ética:");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 117, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 730, 290));

        confirmar.setText("Confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });
        getContentPane().add(confirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 510, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enderecoActionPerformed

    private void bairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bairroActionPerformed

    private void cepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cepActionPerformed

    private void pontoDeReferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pontoDeReferenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pontoDeReferenciaActionPerformed

    private void localizacaoGeograficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localizacaoGeograficaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localizacaoGeograficaActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed

    private void despesasMediasMoradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despesasMediasMoradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_despesasMediasMoradorActionPerformed

    private void totalVagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalVagasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalVagasActionPerformed

    private void vagasOcupadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vagasOcupadasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vagasOcupadasActionPerformed

    private void vagasDisponiveisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vagasDisponiveisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vagasDisponiveisActionPerformed

    private void dataFundacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataFundacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dataFundacaoActionPerformed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmarActionPerformed

    public JTextField getBairro() {
        return bairro;
    }

    public void setBairro(JTextField bairro) {
        this.bairro = bairro;
    }

    public JTextField getCep() {
        return cep;
    }

    public void setCep(JTextField cep) {
        this.cep = cep;
    }

    public JTextArea getCodigoDeEtica() {
        return codigoDeEtica;
    }

    public void setCodigoDeEtica(JTextArea codigoDeEtica) {
        this.codigoDeEtica = codigoDeEtica;
    }

    public JTextField getDataFundacao() {
        return dataFundacao;
    }

    public void setDataFundacao(JTextField dataFundacao) {
        this.dataFundacao = dataFundacao;
    }

    public JTextField getDespesasMediasMorador() {
        return despesasMediasMorador;
    }

    public void setDespesasMediasMorador(JTextField despesasMediasMorador) {
        this.despesasMediasMorador = despesasMediasMorador;
    }

    public JTextField getLocalizacaoGeografica() {
        return localizacaoGeografica;
    }

    public void setLocalizacaoGeografica(JTextField localizacaoGeografica) {
        this.localizacaoGeografica = localizacaoGeografica;
    }

    public JTextField getEndereco() {
        return endereco;
    }

    public void setEndereco(JTextField endereco) {
        this.endereco = endereco;
    }

    public JTextField getNome() {
        return nome;
    }

    public void setNome(JTextField nome) {
        this.nome = nome;
    }

    public JTextField getPontoDeReferencia() {
        return pontoDeReferencia;
    }

    public void setPontoDeReferencia(JTextField pontoDeReferencia) {
        this.pontoDeReferencia = pontoDeReferencia;
    }

    public JTextField getTotalVagas() {
        return totalVagas;
    }

    public void setTotalVagas(JTextField totalVagas) {
        this.totalVagas = totalVagas;
    }

    public JTextField getVagasDisponiveis() {
        return vagasDisponiveis;
    }

    public void setVagasDisponiveis(JTextField vagasDisponiveis) {
        this.vagasDisponiveis = vagasDisponiveis;
    }

    public JTextField getVagasOcupadas() {
        return vagasOcupadas;
    }

    public void setVagasOcupadas(JTextField vagasOcupadas) {
        this.vagasOcupadas = vagasOcupadas;
    }

    public JTextArea getVantagens() {
        return vantagens;
    }

    public void setVantagens(JTextArea vantagens) {
        this.vantagens = vantagens;
    }

    public JTextField getNumero() {
        return numero;
    }

    public void setNumero(JTextField numero) {
        this.numero = numero;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairro;
    private javax.swing.JTextField cep;
    private javax.swing.JTextArea codigoDeEtica;
    private javax.swing.JButton confirmar;
    private javax.swing.JTextField dataFundacao;
    private javax.swing.JTextField despesasMediasMorador;
    private javax.swing.JTextField endereco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField localizacaoGeografica;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField numero;
    private javax.swing.JTextField pontoDeReferencia;
    private javax.swing.JTextField totalVagas;
    private javax.swing.JTextField vagasDisponiveis;
    private javax.swing.JTextField vagasOcupadas;
    private javax.swing.JTextArea vantagens;
    // End of variables declaration//GEN-END:variables
}
