/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.ManterReclamacoesSugestoes;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Davidson
 */
public class P0801View extends javax.swing.JInternalFrame {

    /**
     * Creates new form P0801
     */
    public P0801View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaReclamacaoSugestao = new javax.swing.JTable();
        tipoBusca = new javax.swing.JComboBox<>();
        novaReclamacao = new javax.swing.JButton();
        campoBusca = new javax.swing.JTextField();
        buscarReclamacao = new javax.swing.JButton();
        excluirReclamacao = new javax.swing.JButton();
        editarReclamacao = new javax.swing.JButton();
        confirmarSolucao = new javax.swing.JButton();
        informacoesReclamacao = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);

        tabelaReclamacaoSugestao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Data", "Tipo", "Autor", "Descriçã́o", "Envolvidos", "Finalizada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaReclamacaoSugestao.setRowHeight(25);
        jScrollPane1.setViewportView(tabelaReclamacaoSugestao);

        tipoBusca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pessoa", "Descrição" }));

        novaReclamacao.setText("Cadastrar Nova Sugestão / Reclamação");
        novaReclamacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaReclamacaoActionPerformed(evt);
            }
        });

        campoBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoBuscaActionPerformed(evt);
            }
        });

        buscarReclamacao.setText("Buscar");
        buscarReclamacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarReclamacaoActionPerformed(evt);
            }
        });

        excluirReclamacao.setText("Excluir");
        excluirReclamacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirReclamacaoActionPerformed(evt);
            }
        });

        editarReclamacao.setText("Editar");
        editarReclamacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarReclamacaoActionPerformed(evt);
            }
        });

        confirmarSolucao.setText("Confirmar Solução");
        confirmarSolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarSolucaoActionPerformed(evt);
            }
        });

        informacoesReclamacao.setText("Ver Informações");
        informacoesReclamacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informacoesReclamacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tipoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscarReclamacao, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(novaReclamacao, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(confirmarSolucao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(informacoesReclamacao)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(excluirReclamacao, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(editarReclamacao, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarReclamacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(novaReclamacao)
                    .addComponent(editarReclamacao)
                    .addComponent(excluirReclamacao)
                    .addComponent(informacoesReclamacao)
                    .addComponent(confirmarSolucao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void novaReclamacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaReclamacaoActionPerformed
    }//GEN-LAST:event_novaReclamacaoActionPerformed

    private void campoBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoBuscaActionPerformed

    private void buscarReclamacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarReclamacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarReclamacaoActionPerformed

    private void excluirReclamacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirReclamacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_excluirReclamacaoActionPerformed

    private void editarReclamacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarReclamacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarReclamacaoActionPerformed

    private void confirmarSolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarSolucaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmarSolucaoActionPerformed

    private void informacoesReclamacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informacoesReclamacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_informacoesReclamacaoActionPerformed

    public JButton getBuscarReclamacao() {
        return buscarReclamacao;
    }

    public JTextField getCampoBusca() {
        return campoBusca;
    }

    public JButton getConfirmarSolucao() {
        return confirmarSolucao;
    }

    public JButton getEditarReclamacao() {
        return editarReclamacao;
    }

    public JButton getExcluirReclamacao() {
        return excluirReclamacao;
    }

    public JButton getInformacoesReclamacao() {
        return informacoesReclamacao;
    }

    public JButton getNovaReclamacao() {
        return novaReclamacao;
    }

    public JTable getTabelaReclamacaoSugestao() {
        return tabelaReclamacaoSugestao;
    }

    public JComboBox<String> getTipoBusca() {
        return tipoBusca;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarReclamacao;
    private javax.swing.JTextField campoBusca;
    private javax.swing.JButton confirmarSolucao;
    private javax.swing.JButton editarReclamacao;
    private javax.swing.JButton excluirReclamacao;
    private javax.swing.JButton informacoesReclamacao;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton novaReclamacao;
    private javax.swing.JTable tabelaReclamacaoSugestao;
    private javax.swing.JComboBox<String> tipoBusca;
    // End of variables declaration//GEN-END:variables
}
