/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.ManterReclamacoesSugestoes;

import view.ManterTarefa.P0302;
import view.P0000View;

/**
 *
 * @author Davidson
 */
public class P0801 extends javax.swing.JInternalFrame {

    /**
     * Creates new form P0801
     */
    public P0801() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        novaReclamacao = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        buscarReclamacao = new javax.swing.JButton();
        excluirReclamacao = new javax.swing.JButton();
        editarReclamacao = new javax.swing.JButton();
        confirmarSolucao = new javax.swing.JButton();
        informacoesReclamacao = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Data", "Tipo", "Autor", "Descriçã́o", "Envolvidos", "Finalizada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pessoa", "Descrição" }));

        novaReclamacao.setText("Cadastrar Nova Sugestão / Reclamação");
        novaReclamacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novaReclamacaoActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        buscarReclamacao.setText("Buscar");
        buscarReclamacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarReclamacaoActionPerformed(evt);
            }
        });

        excluirReclamacao.setText("Excluir");
        excluirReclamacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirReclamacaoActionPerformed(evt);
            }
        });

        editarReclamacao.setText("Editar");
        editarReclamacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarReclamacaoActionPerformed(evt);
            }
        });

        confirmarSolucao.setText("Confirmar Solução");
        confirmarSolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarSolucaoActionPerformed(evt);
            }
        });

        informacoesReclamacao.setText("Ver Informações");
        informacoesReclamacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informacoesReclamacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 872, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(novaReclamacao, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(170, 170, 170)
                            .addComponent(confirmarSolucao)
                            .addGap(11, 11, 11)
                            .addComponent(informacoesReclamacao)
                            .addGap(9, 9, 9)
                            .addComponent(excluirReclamacao, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(editarReclamacao, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(6, 6, 6)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(9, 9, 9)
                                    .addComponent(buscarReclamacao, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buscarReclamacao))
                    .addGap(20, 20, 20)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(13, 13, 13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(novaReclamacao)
                        .addComponent(confirmarSolucao)
                        .addComponent(informacoesReclamacao)
                        .addComponent(excluirReclamacao)
                        .addComponent(editarReclamacao))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void novaReclamacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novaReclamacaoActionPerformed
        P0302 cad = new P0302();
        P0000View.Desktop.add(cad);
        cad.setVisible(true);
    }//GEN-LAST:event_novaReclamacaoActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void buscarReclamacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarReclamacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarReclamacaoActionPerformed

    private void excluirReclamacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirReclamacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_excluirReclamacaoActionPerformed

    private void editarReclamacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarReclamacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarReclamacaoActionPerformed

    private void confirmarSolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarSolucaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_confirmarSolucaoActionPerformed

    private void informacoesReclamacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informacoesReclamacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_informacoesReclamacaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarReclamacao;
    private javax.swing.JButton confirmarSolucao;
    private javax.swing.JButton editarReclamacao;
    private javax.swing.JButton excluirReclamacao;
    private javax.swing.JButton informacoesReclamacao;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton novaReclamacao;
    // End of variables declaration//GEN-END:variables
}
